# Generated by Django 4.0.3 on 2022-03-31 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(help_text='Enter last name', max_length=255, verbose_name='Last name')),
                ('ccms_id', models.IntegerField(help_text='Enter CCMS ID', unique=True, verbose_name='CCMS ID')),
                ('phone', models.CharField(help_text='Enter phone number', max_length=255, verbose_name='Phone')),
                ('email', models.CharField(help_text='Enter email address', max_length=255, verbose_name='Email')),
                ('country', models.CharField(help_text='Enter country', max_length=255, verbose_name='Country')),
                ('city', models.CharField(help_text='Enter city', max_length=255, verbose_name='City')),
                ('street', models.CharField(help_text='Enter street and building number.', max_length=400, verbose_name='Street')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(help_text='Enter serial number', max_length=400, null=True, unique=True, verbose_name='Serial number')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(help_text='Enter manufacturer name', max_length=255, unique=True, verbose_name='Manufacturer')),
                ('model', models.CharField(help_text='Enter model name', max_length=255, unique=True, verbose_name='Model')),
                ('type', models.CharField(help_text='Enter type of equipement', max_length=255, unique=True, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Enter project name', max_length=255, unique=True, verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=2000, null=True, verbose_name='Comment')),
                ('status', models.CharField(blank=True, choices=[('g', 'Given'), ('r', 'Returned')], default='r', help_text='Status', max_length=1)),
                ('agent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facility.agent')),
                ('equipement_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='facility.equipement')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='equipement',
            name='manufacturer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='facility.manufacturers'),
        ),
        migrations.AddField(
            model_name='agent',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='facility.project'),
        ),
    ]
