# Generated by Django 4.0.3 on 2022-03-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='ccms_id',
            field=models.CharField(help_text='Enter CCMS ID', max_length=255, unique=True, verbose_name='CCMS ID'),
        ),
    ]
