# Generated by Django 4.0.3 on 2022-03-31 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_alter_agent_ccms_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_model', models.CharField(help_text='Enter model name', max_length=255, unique=True, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Enter type of equipement', max_length=255, unique=True, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Equipement type',
                'verbose_name_plural': 'Equipement types',
            },
        ),
        migrations.RemoveField(
            model_name='manufacturers',
            name='model',
        ),
        migrations.RemoveField(
            model_name='manufacturers',
            name='type',
        ),
        migrations.AlterField(
            model_name='equipement',
            name='manufacturer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufactequipements', to='facility.manufacturers'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='eqModels_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelsequipements', to='facility.eqmodels'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='types_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typesequipements', to='facility.types'),
        ),
    ]
