# Generated by Django 4.0.3 on 2022-03-31 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_eqmodels_types_remove_manufacturers_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='equipement_id',
        ),
        migrations.AddField(
            model_name='order',
            name='eqModels_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelsequipements', to='facility.eqmodels'),
        ),
        migrations.AddField(
            model_name='order',
            name='manufacturer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufactequipements', to='facility.manufacturers'),
        ),
        migrations.AddField(
            model_name='order',
            name='sn',
            field=models.CharField(help_text='Enter serial number', max_length=400, null=True, unique=True, verbose_name='Serial number'),
        ),
        migrations.AddField(
            model_name='order',
            name='types_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typesequipements', to='facility.types'),
        ),
        migrations.DeleteModel(
            name='Equipement',
        ),
    ]
