# Generated by Django 4.0.3 on 2022-04-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_remove_order_equipement_id_order_eqmodels_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='eqModels_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='manufacturer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='types_id',
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(help_text='Enter serial number', max_length=400, null=True, unique=True, verbose_name='Serial number')),
                ('status', models.CharField(blank=True, choices=[('g', 'Given'), ('r', 'Returned')], default='r', help_text='Status', max_length=1)),
                ('eqModels_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelsequipements', to='facility.eqmodels')),
                ('manufacturer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufactequipements', to='facility.manufacturers')),
                ('types_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typesequipements', to='facility.types')),
            ],
            options={
                'verbose_name': 'Order line',
                'verbose_name_plural': 'Order lines',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='orderline_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='facility.orderline'),
        ),
    ]
