# Generated by Django 4.0.3 on 2022-04-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0005_remove_order_eqmodels_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderline_id',
        ),
        migrations.AddField(
            model_name='orderline',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='facility.order'),
        ),
    ]
