# Generated by Django 4.0.3 on 2022-04-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0008_remove_orderline_eqmodels_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipement',
            options={'verbose_name': 'Equipement', 'verbose_name_plural': 'Equipements'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(help_text='Enter email address', max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='agent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordersall', to='facility.agent'),
        ),
    ]
